import { HotelImage } from "../constants/index";

export const HOTELS = [
  {
    id: 1,
    name: "Protea Hotel by Marriott Benin City Select Emotan",
    address: "4 Central Rd, Off Sapele Road, Benin City, Nigeria",
    lat: 6.3205,
    lng: 5.6037,
    rating: "★★★★",
    distance: "1.9 mi",
    time: "4 min",
    bookBefore: "Sep 30, 2025",
    rate: 65,
    images: HotelImage.slice(15, 18).map((img) => img.src),
  },

  {
    id: 2,
    name: "De Brit Hotel",
    address: "70 Ihama Road G.R.A Benin City Nigeria",
    lat: 6.315,
    lng: 5.61,
    rating: "★★★★",
    distance: "2.0 mi",
    time: "5 min",
    bookBefore: "Sep 30, 2025",
    rate: 70,
    images: HotelImage.slice(21, 24).map((img) => img.src),
  },
  {
    id: 3,
    name: "Eterno Hotel",
    address: "103B Aiguobasinwin Crescent Off Ikpopan Road, Benin City",
    lat: 6.2786,
    lng: 5.625,
    rating: "★★★★",
    distance: "2.5 mi",
    time: "6 min",
    bookBefore: "Sep 30, 2025",
    rate: 80,
    images: HotelImage.slice(6, 9).map((img) => img.src),
  },
  {
    id: 4,
    name: "Constantial Hotel",
    address: "24-26 Airport road, opposite the Airport exit gate in Benin City",
    lat: 6.317,
    lng: 5.599,
    rating: "★★★★",
    distance: "1.5 mi",
    time: "3 min",
    bookBefore: "Sep 30, 2025",
    rate: 90,
    images: HotelImage.slice(12, 15).map((img) => img.src),
  },
  {
    id: 5,
    name: "Prestige Hotel",
    address: "1 Ihama Rd, Benin City",
    lat: 6.35,
    lng: 5.63,
    rating: "★★★★",
    distance: "3.0 mi",
    time: "7 min",
    bookBefore: "Sep 30, 2025",
    rate: 100,
    images: HotelImage.slice(3, 6).map((img) => img.src),
  },
  {
    id: 6,
    name: "Randekhi Gold",
    address: "6 Uhenuyi St uddoh Street GRA Benin City",
    lat: 6.34,
    lng: 5.64,
    rating: "★★★★",
    distance: "2.2 mi",
    time: "5 min",
    bookBefore: "Sep 30, 2025",
    rate: 55,
    images: HotelImage.slice(18, 21).map((img) => img.src),
  },
  {
    id: 7,
    name: "Kawruky Hotel Benin",
    address: "Idusogie Street, Benin City",
    lat: 6.33,
    lng: 5.61,
    rating: "★★★★",
    distance: "1.8 mi",
    time: "4 min",
    bookBefore: "Sep 30, 2025",
    rate: 75,
    images: HotelImage.slice(9, 12).map((img) => img.src),
  },
];
